language: java
cache:
  directories:
    - $HOME/.m2
install:
    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - java -jar BuildTools.jar --rev 1.8 2>&1 >/dev/null
    - java -jar BuildTools.jar --rev 1.8.3 2>&1 >/dev/null
    - java -jar BuildTools.jar --rev 1.8.8 2>&1 >/dev/null
    - java -jar BuildTools.jar --rev 1.9 2>&1 >/dev/null
    - java -jar BuildTools.jar --rev 1.9.4 2>&1 >/dev/null
    - java -jar BuildTools.jar --rev 1.10.2 2>&1 >/dev/null
    - java -jar BuildTools.jar --rev 1.11.2 2>&1 >/dev/null
    - java -jar BuildTools.jar --rev 1.12.2 2>&1 >/dev/null
script:
    - mvn clean install
    - cd api && mvn clean install